name: Track External Valkey-Glide Mentions

on:
  workflow_dispatch:  # Allows manual execution
  schedule:
    - cron: "0 * * * *" # Runs every hour

jobs:
  search_mentions:
    runs-on: ubuntu-latest
    steps:
      - name: Search GitHub Mentions Excluding Own Repo (Last Week)
        run: |
          LAST_WEEK=$(date -d "7 days ago" +"%Y-%m-%d")
          curl -s "https://api.github.com/search/issues?q=valkey-glide+-repo:valkey-io/valkey-glide+-repo:glide-for-redis+-repo:valkey-glide+-repo:github-trending-repos+updated:>$LAST_WEEK" | jq '.items[] | {title,html_url, updated_at}'
